name: CI

on:
  create:
    branches: 
      - release/**
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: TraderShop.Financials.TdAmeritrade.sln

    runs-on: ubuntu-latest

    steps:
    - name: Setting up actions
      uses: actions/checkout@v3
      env:
        API_KEY: oy2e7vwpckbbnbf52bia4yjltuk5uaeebd25tbznmfmtdq
      
    
    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name : Clean
      run : dotnet Clean

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

    - name: Pack
      run: dotnet pack --configuration $BUILD_CONFIG  --no-build --output .
    # - name: Run tests
    #   run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
      
    - name: Publish
      # if: startsWith(github.ref, 'refs/heads/release')
      run: nuget push **\*.nupkg --api-key API_KEY -Source 'https://api.nuget.org/v3/index.json' 
