name: CI

on:
  create:
    branches: 
      - release/**
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: TraderShop.Financials.TdAmeritrade.sln
      API_KEY: ${{ secrets.NUGET_API_KEY }}

    runs-on: ubuntu-latest

    steps:
    - name: Setting up actions
      uses: actions/checkout@v3
        

      
    
    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x


    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name : Clean
      run : dotnet Clean

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

    - name: Publish
      # if: startsWith(github.ref, 'refs/heads/release')
      run: dotnet nuget push **\*.nupkg -k oy2nishnhgyuay2dxisqt3rdv4mejo6ubgftikt43djflq -s https://api.nuget.org/v3/index.json --skip-duplicate
